sonar.projectKey=prueba_backend
sonar.organization=sfb (Solo para SonarCloud)
sonar.host.url=https://sonarcloud.io (O la URL de tu servidor)
sonar.login=${env.SONAR_TOKEN}
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.tests=tests
sonar.exclusions=**/*.test.ts, **/node_modules/**
sonar.coverage.exclusions=**/test/**
